export var lstFiltes = [
  "buffer overflow",
  "denial of service",
  "heap overflow",
  "sql injection",
  "remote attackers to execute",
  "directory traversal vulnerability",
  "remote attackers to read",
  "xss",
  "cross-site scripting",
  "cross site scripting",
  "allows remote attackers to inject",
  "allows remote authenticated",
  "allows remote attackers to use a certificate",
  "stack-based buffer overflow",
  "stack based buffer overflow",
  "allows local users to bypass",
  "allows local users to obtain",
  "cross-site request",
  "cross site request",
  "allows local users to expose",
  "allows remote attackers to gain root",
  "allows remote attackers to monitor",
  "allows remote attackers to trick",
  "allows remote attackers to view",
  "heap corruption",
  "allows local users to gain privileges",
  "allows local users to overwrite",
  "allows remote attackers to trigger memory corruption or possibly execute",
  "possibly execute",
  "allow remote attackers to modify",
  "privilege escalation",
  "remote attacker",
  "remote bypass",
  "remote code execution",
  "elevation of privilege",
];
